name: Get version

on:
  workflow_call:
    # Map workflow outputs to job outputs.
    outputs:
      VERSION_STRING:
        value: ${{ jobs.get-version.outputs.VERSION_STRING }}

# Restrict permissions of GITHUB_TOKEN
# Access to scopes not specified is set to "none"
permissions:
  contents: read

env:
  VERSION_STRING: ""
  VERSION_TAG_REGEX: '^.*/[0-9]+\.[0-9]+\.[0-9]+$'

defaults:
  run:
    shell: bash

jobs:
  get-version:
    runs-on: ubuntu-latest

    # Map step outputs to job outputs.
    outputs:
      VERSION_STRING: ${{ steps.return-version.outputs.VERSION_STRING }}

    steps:
      - name: Extract version
        id: extract-version
        run: |
          if [[ ${{ github.ref_name }} =~ ${{ env.VERSION_TAG_REGEX }} ]]; then
            echo "VERSION_STRING=$( \
            echo ${{ github.ref_name }} \
            | grep -Po "^.*/\K\d.\d.\d$" )" >> $GITHUB_ENV
          fi          

      - name: Return VERSION_STRING
        id: return-version
        run: |
             echo "::notice title=VERSION_STRING::✅ VERSION_STRING: ${{ env.VERSION_STRING }} ."
             echo "VERSION_STRING=${{ env.VERSION_STRING }}" >> $GITHUB_OUTPUT
