name: Tag ref as build

on:
  workflow_call:
    # Map workflow outputs to job outputs.
    outputs:
      BUILD_NUMBER:
        value: ${{ jobs.tag-ref-as-build.outputs.BUILD_NUMBER }}
      BUILD_TAG:
        value: ${{ jobs.tag-ref-as-build.outputs.BUILD_TAG }}

# Restrict permissions of GITHUB_TOKEN
# Access to scopes not specified is set to "none"
permissions:
  contents: write

env:
  CURL_OPTIONS: "--fail-with-body --location --show-error --silent"

defaults:
  run:
    shell: bash

jobs:
  get-next-build:
    uses: polarlabs/factory/.github/workflows/get-next-build.yml@v/1.0.0

  tag-ref-as-build:
    runs-on: ubuntu-latest
    needs: [get-next-build]

    # Map step outputs to job outputs.
    outputs:
      BUILD_NUMBER: ${{ steps.return-build.outputs.BUILD_NUMBER }}
      BUILD_TAG: ${{ steps.return-build.outputs.BUILD_TAG }}

    steps:
      - name: Create annotated tag object
        id: create-annotated-tag-object
        env:
          BUILD_TAG: ${{ needs.get-next-build.outputs.BUILD_TAG }}
        run: |
          curl ${{ env.CURL_OPTIONS }} \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               ${{ github.api_url }}/repos/${{ github.repository }}/git/tags \
               --data '{ "tag": "${{ env.BUILD_TAG }}", 
                         "message": "auto incremented build number",  
                         "object": "${{ github.sha }}", 
                         "type": "commit" }'

      - name: Tag ref as build
        id: tag-ref-as-build
        env:
          BUILD_TAG: ${{ needs.get-next-build.outputs.BUILD_TAG }}
        run: |
          curl ${{ env.CURL_OPTIONS }} \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               ${{ github.api_url }}/repos/${{ github.repository }}/git/refs \
               --data '{ "ref": "refs/tags/${{ env.BUILD_TAG }}", 
                         "sha": "${{ github.sha }}" }'

      - name: Return BUILD_NUMBER and BUILD_TAG
        id: return-build
        run: |
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}" >> $GITHUB_OUTPUT
          echo "BUILD_TAG=${{ env.BUILD_TAG_PREFIX}}/${{ env.BUILD_NUMBER }}" >> $GITHUB_OUTPUT
